import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "About Us",
    description: "Generated by create next app",
    authors: [
        { name: "Musawer" },
        { name: "Ahmad", url: "musawerxd.com" },
    ],
};

export default function ServiceLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return <section>{children}</section>;
}